
site_name: "dagpiler"
site_author: "Mitchell Tillman"
repo_name: ""
repo_url: "https://github.com/ResearchOS/dagpiler"
site_url: "https://researchos.github.io//"
theme:
  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.top
    - content.code.copy

plugins:
  - search  
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_signature: true
            show_docstrings: true
          selection:
            members: true
            docstring_style: "google"
          options:
            filters:
              - "!^__.*__$"
              - "!^_"

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - admonition
# nav:
#   - Home: index.md
#   - Config Files:
#     - Config Files: toml_files.md
#   - Packaging:
#     - Installation: Packaging/installing_packages.md
#     - Publishing: Packaging/publishing_packages.md
#     - Folder Structure: Packaging/folder_structure.md
#   - Dictionary: terms.md  
#   - Dev Blog:
#     - Dev Blog: "Dev_Blog/*.md"

