
site_name: "Package-DAG-Compiler"
site_author: "Mitchell Tillman"
repo_name: ""
repo_url: "https://github.com//"
site_url: "https://researchos.github.io//"
theme:
  name: material
  features:
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - navigation.top

plugins:
  - search  
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
            show_signature: true
            show_docstrings: true
          selection:
            members: true
            docstring_style: "google"
          options:
            filters:
              - "!^__.*__$"
              - "!^_"

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - admonition
nav:
  - Home: docs/index.md

